Fix cherry-pick build status

diff --git a/.github/workflows/CherryPickTest.yml b/.github/workflows/CherryPickTest.yml
--- a/.github/workflows/CherryPickTest.yml
+++ b/.github/workflows/CherryPickTest.yml
@@ -95,8 +95,8 @@ jobs:
               exit 0
               ;;
             skipped)
-              echo "::notice::No builds were required"
-              exit 0
+              echo "::notice::Builds were skipped because of an earlier failure"
+              exit 1
               ;;
               *)
               echo "::error::One or more builds failed" 
