add sync jobs to cherry pick

diff --git a/.github/workflows/CherryPickTest.yml b/.github/workflows/CherryPickTest.yml
--- a/.github/workflows/CherryPickTest.yml
+++ b/.github/workflows/CherryPickTest.yml
@@ -74,8 +74,31 @@ jobs:
           github-token:      ${{secrets.GITHUB_TOKEN}}
           modules-blacklist: ${{env.MODULES_BLACKLIST}}
 
-  AsteriskUnitTestMatrix:
+  AsteriskBuilds:
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
     needs: AsteriskBuildMatrix
+    steps:
+      - name: Check build matrix status
+        env:
+          RESULT: ${{needs.AsteriskBuildMatrix.result}}
+        run: |
+          case $RESULT in
+            success)
+              echo "::notice::All builds succeeded"
+              exit 0
+              ;;
+            skipped)
+              echo "::notice::No builds were required"
+              exit 0
+              ;;
+              *)
+              echo "::error::One or more builds failed" 
+              exit 1
+          esac
+
+  AsteriskUnitTestMatrix:
+    needs: AsteriskBuilds
     continue-on-error: false
     strategy:
       fail-fast: true
@@ -101,8 +124,31 @@ jobs:
           github-token:      ${{secrets.GITHUB_TOKEN}}
           unittest-command:  ${{vars.UNITTEST_COMMAND}}
 
-  AsteriskGateTestMatrix:
+  AsteriskUnitTests:
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
     needs: AsteriskUnitTestMatrix
+    steps:
+      - name: Check unit test matrix status
+        env:
+          RESULT: ${{needs.AsteriskUnixTestMatrix.result}}
+        run: |
+          case $RESULT in
+            success)
+              echo "::notice::All tests passed"
+              exit 0
+              ;;
+            skipped)
+              echo "::notice::No tests were required"
+              exit 0
+              ;;
+              *)
+              echo "::error::One or more tests failed" 
+              exit 1
+          esac
+
+  AsteriskGateTestMatrix:
+    needs: AsteriskUnitTests
     if: ${{ success() }}
     continue-on-error: true
     strategy:
