Update nightly for new actions

diff --git a/.github/workflows/NightlyJob.yml b/.github/workflows/NightlyJob.yml
--- a/.github/workflows/NightlyJob.yml
+++ b/.github/workflows/NightlyJob.yml
@@ -5,30 +5,15 @@ on:
 #    - cron: '0 2 * * *'
 
 env:
-  CACHE_KEY: Nightly-RUN:${{ github.run_number }}-RID:${{ github.run_id }}
+  ASTERISK_REPO:     ${{ github.repository }}
+  PR_NUMBER:         ${{ github.event.number }}
+  PR_COMMIT:         ${{ github.event.pull_request.head.sha }}
+  GITHUB_TOKEN:      ${{ secrets.GITHUB_TOKEN }}
+  GH_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
+  MODULES_BLACKLIST: ${{ vars.GATETEST_MODULES_BLACKLIST }} ${{ vars.UNITTEST_MODULES_BLACKLIST }}
 
 jobs:
-  AsteriskNightlyBuildMatrix:
-    continue-on-error: false
-    strategy:
-      fail-fast: true
-      matrix:
-        branch: ${{ fromJSON(vars.NIGHTLYTEST_BRANCHES) }}
-    runs-on: ubuntu-latest
-    container:
-      image: ghcr.io/asterisk/asteriskci-agent-rocky8:latest
-    steps:
-      - name: Build Asterisk for branch ${{ matrix.branch }}
-        uses: asterisk/asterisk-ci-actions/GetAsterisk@main
-        with:
-          to-cache-key: ${{env.CACHE_KEY}}-${{ matrix.branch }}
-          base-branch: ${{ matrix.branch }}
-          modules-blacklist: ${{ vars.NIGHTLYTEST_MODULES_BLACKLIST }}
-
   AsteriskNightlyTestMatrix:
-    name: AsteriskNightlyTestMatrix
-    if: ${{ success() }}
-    needs: AsteriskNightlyBuildMatrix
     continue-on-error: true
     strategy:
       fail-fast: false
@@ -36,35 +21,58 @@ jobs:
         branch: ${{ fromJSON(vars.NIGHTLYTEST_BRANCHES) }}
         group: ${{ fromJSON(vars.NIGHTLYTEST_LIST) }}
     runs-on: ubuntu-latest
-    container:
-      image: ghcr.io/asterisk/asteriskci-agent-rocky8:latest
     steps:
-      - name: Install Asterisk for branch ${{ matrix.branch }}
+      - name: Install Asterisk
         uses: asterisk/asterisk-ci-actions/GetAsterisk@main
         with:
-          from-cache-key: ${{env.CACHE_KEY}}-${{ matrix.branch }}
-          base-branch: ${{ matrix.branch }}
-          modules-blacklist: ${{ vars.NIGHTLYTEST_MODULES_BLACKLIST }}
-
-      - name: Run Gate Tests for branch ${{ matrix.branch }} group ${{ matrix.group }}
+          asterisk_repo:     ${{env.ASTERISK_REPO}}
+          base_branch:       ${{matrix.branch}}
+          pr_number:         ${{env.PR_NUMBER}}
+          github_token:      ${{secrets.GITHUB_TOKEN}}
+          modules_blacklist: ${{env.MODULES_BLACKLIST}}
+    
+      - name: Run Gate Tests for group ${{ matrix.group }} branch ${{ matrix.branch }} 
         uses: asterisk/asterisk-ci-actions/RunAsteriskGateTests@main
         with:
-          asterisk-repo:     ${{ github.repository }}
-          base-branch:       ${{ matrix.branch }}
-          github-token:      ${{ secrets.GITHUB_TOKEN }}
-          testsuite-repo:    ${{ vars.TESTSUITE_REPO }}
-          gatetest-group:    ${{ matrix.group }}
-          gatetest-commands: ${{ vars.GATETEST_COMMANDS }} 
+          asterisk_repo:     ${{env.ASTERISK_REPO}}
+          pr_number:         ${{env.PR_NUMBER}}
+          base_branch:       ${{matrix.branch}}
+          github_token:      ${{secrets.GITHUB_TOKEN}}
+          testsuite_repo:    ${{vars.TESTSUITE_REPO}}
+          gatetest_group:    ${{matrix.group}}
+          gatetest_commands: ${{vars.GATETEST_COMMANDS}} 
+
+      - name: Save Output
+        id: save-output
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: Nightly Test Output for for group ${{ matrix.group }} branch ${{ matrix.branch }}
+          path: testsuite/logs
+
+      - name: Publish Unit Test Results
+        id: publish-results
+        if: always()
+        uses: EnricoMi/publish-unit-test-result-action@v2.4.2
+        with:
+          check_name: Nightly Test Results
+          comment_title: Gate Test Results for group ${{ matrix.group }} branch ${{ matrix.branch }}
+          files: testsuite/*.xml
+          comment_mode: always
+          compare_to_earlier_commit: false
+          report_individual_runs: true
+          action_fail: true
+        env:
+          GITHUB_REPOSITORY: ${{env.ASTERISK_REPO}}
 
   AsteriskNightlyTests:
-    name: AsteriskNightlyTests
     if: ${{ always() }}
     runs-on: ubuntu-latest
     needs: AsteriskNightlyTestMatrix
     steps:
       - name: Check test matrix status
         env:
-          RESULT: ${{ needs.AsteriskNightlyTestMatrix.result }}
+          RESULT: ${{needs.AsteriskNightlyTestMatrix.result}}
         run: |
           case $RESULT in
             success)
@@ -72,21 +80,10 @@ jobs:
               exit 0
               ;;
             skipped)
-              echo "::notice::No Testsuite tests were required"
-              exit 0
+              echo "::error::Testsuite tests were skipped because of an earlier failure"
+              exit 1
               ;;
               *)
               echo "::error::One or more Testsuite tests failed" 
               exit 1
           esac
-
-  DeleteCache:
-    if: ${{ always() }}
-    runs-on: ubuntu-latest
-    needs: AsteriskNightlyTests
-    steps:
-      - name: DeleteCache
-        uses: snnaplab/delete-branch-cache-action@v1
-        with:
-          ref: refs/heads/master
-          key: ${{env.CACHE_KEY}}
