OnPRStatChanged,OnPRRecheck: Refactor to include job summary

diff --git a/.github/workflows/OnPRCherryPickTest.yml b/.github/workflows/OnPRCherryPickTest.yml
--- a/.github/workflows/OnPRCherryPickTest.yml
+++ b/.github/workflows/OnPRCherryPickTest.yml
@@ -1,74 +1,97 @@
 name: PRCPCheck
-run-name: "PR ${{ github.event.number }} CherryPickTest"
+run-name: "PR ${{ github.event.number }} CherryPickTest by ${{ github.actor }}"
 on:
   pull_request_target:
     types: [ labeled ]
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.event.label.name }}-${{ github.event.number }}
+  group: ${{ github.event.label.name }}-${{ github.event.number }}
   cancel-in-progress: true
 
 env:
+  REPO:      ${{ github.repository }}
   PR_NUMBER: ${{ github.event.number }}
+  WORKFLOW_RUN_ID:   ${{ github.run_id }}
+  SCRIPT_DIR:        ${{ github.workspace }}/asterisk-ci-actions/scripts
+  GH_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
 
 jobs:
   Setup:
-    if: ${{ github.event.label.name == vars.CHERRY_PICK_TEST_LABEL }}
     name: Setup
     runs-on: ubuntu-latest
     outputs:
-      branches:           ${{ steps.getbranches.outputs.branches }}
-      branch_count:       ${{ steps.getbranches.outputs.branch_count }}
-      testsuite_test_pr:  ${{ steps.testsuitepr.outputs.testsuite_test_pr }}
+      branches:           ${{ steps.setup.outputs.BRANCHES }}
+      branch_count:       ${{ steps.setup.outputs.BRANCH_COUNT }}
+      testsuite_test_pr:  ${{ steps.setup.outputs.TESTSUITE_TEST_PR }}
     steps:
-      - name: Remove Trigger Label, Add InProgress Label
+      - id: setup
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          CHERRY_PICK_TEST_LABEL:          ${{ vars.CHERRY_PICK_TEST_LABEL }}
+          CHERRY_PICK_CHECKS_PASSED_LABEL: ${{ vars.CHERRY_PICK_CHECKS_PASSED_LABEL }}
+          CHERRY_PICK_CHECKS_FAILED_LABEL: ${{ vars.CHERRY_PICK_CHECKS_FAILED_LABEL }}
+          CHERRY_PICK_TESTING_IN_PROGRESS: ${{ vars.CHERRY_PICK_TESTING_IN_PROGRESS }}
+          CHERRY_PICK_REGEX:               ${{ vars.CHERRY_PICK_REGEX }}
+          TESTSUITE_TEST_PR_REGEX:         ${{ vars.TESTSUITE_TEST_PR_REGEX }}
         run: |
-          gh pr edit --repo ${{ github.repository }} \
-            --remove-label ${{ vars.CHERRY_PICK_TEST_LABEL }} \
-            --remove-label ${{ vars.CHERRY_PICK_CHECKS_PASSED_LABEL }} \
-            --remove-label ${{ vars.CHERRY_PICK_CHECKS_FAILED_LABEL }} \
-            --remove-label ${{ vars.CHERRY_PICK_TESTING_IN_PROGRESS }} \
-            $PR_NUMBER || :
+          # Setup
+          wget -qO asterisk-ci-actions.tar.gz \
+            https://github.com/${ACTIONS_OWNER}/${ACTIONS_REPO}/archive/refs/heads/${ACTIONS_BRANCH}.tar.gz
+          tar -xf asterisk-ci-actions.tar.gz --transform="s/^${ACTIONS_REPO}-${ACTIONS_BRANCH}/asterisk-ci-actions/g"
 
-      - name: Get cherry-pick branches
-        uses: asterisk/asterisk-ci-actions/GetCherryPickBranchesFromPR@main
-        id: getbranches
-        with:
-          repo:                    ${{ github.repository }}
-          pr_number:               ${{ env.PR_NUMBER }}
-          cherry_pick_regex:       ${{ vars.CHERRY_PICK_REGEX }}
-          github_token:            ${{ secrets.GITHUB_TOKEN }}
+          gh pr edit --repo ${REPO} \
+            --remove-label ${CHERRY_PICK_TEST_LABEL} \
+            --remove-label ${CHERRY_PICK_CHECKS_PASSED_LABEL} \
+            --remove-label ${CHERRY_PICK_CHECKS_FAILED_LABEL} \
+            --remove-label ${CHERRY_PICK_TESTING_IN_PROGRESS} \
+            ${PR_NUMBER} || :
 
-      - name: Check Branch Count
-        if: ${{ steps.getbranches.outputs.branch_count > 0 }}
+          # The script will populate BRANCHES and BRANCH_COUNT in
+          # both GITHUB_ENV and GITHUB_OUTPUT for future use but
+          # we need them here as well so we need to capture and
+          # parse the output.
+          result=$(${SCRIPT_DIR}/getCherryPickBranchesFromPR.sh \
+            --repo=${REPO} \
+            --pr-number=${PR_NUMBER} \
+            --cherry-pick-regex="${CHERRY_PICK_REGEX}")
+          BRANCH_COUNT=$(echo ${result} | jq -c '.branch_count')
+          BRANCHES=$(echo ${result} | jq -c '.branches')
+          FORCED_NONE=$(echo ${result} | jq -c '.forced_none')
+
+          if [ ${BRANCH_COUNT} -eq 0 ] ; then
+            echo "No cherry-pick branches"
+            exit 0
+          fi
+
+          gh pr edit --repo ${REPO} \
+            --add-label ${CHERRY_PICK_TESTING_IN_PROGRESS} \
+            ${PR_NUMBER} || :
+
+          # The script will populate TESTSUITE_TEST_PR in both
+          # GITHUB_ENV and GITHUB_OUTPUT.
+          ${SCRIPT_DIR}/getTestsuitePRfromAsteriskPR.sh \
+            --repo=${REPO} \
+            --pr-number=${PR_NUMBER} \
+            --testsuite-pr-regex="${TESTSUITE_TEST_PR_REGEX}"
+
+      - name: CheckCherryPicks
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BRANCHES: ${{ steps.prestart.outputs.branches }}
         run: |
-          gh pr edit --repo ${{ github.repository }} \
-          --add-label ${{ vars.CHERRY_PICK_TESTING_IN_PROGRESS }} \
-          $PR_NUMBER || :
+          ${SCRIPT_DIR}/cherryPick.sh \
+            --repo=${REPO} \
+            --repo-dir=${REPO_DIR} \
+            --pr-number=${PR_NUMBER} \
+            --output-dir=./logs \
+            --branches="${BRANCHES}"
 
-      - name: GetTestsuitePR
-        id: testsuitepr
-        uses: asterisk/asterisk-ci-actions/GetTestsuitePRFromAsteriskPR@main
+      - name: Save Output
+        id: save-output
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v4
         with:
-          repo:                            ${{ github.repository }}
-          pr_number:                       ${{ github.event.number }}
-          testsuite_test_pr_regex:         ${{ vars.TESTSUITE_TEST_PR_REGEX }}
-          testsuite_test_auto_merge_regex: ${{ vars.TESTSUITE_TEST_AUTO_MERGE_REGEX }}
-          github_token:                    ${{ secrets.GITHUB_TOKEN }}
-
-      - name: CherryPick
-        uses: asterisk/asterisk-ci-actions/CherryPick@main
-        with:
-          repo:         ${{ github.repository }}
-          pr_number:    ${{ github.event.number }}
-          branches:     ${{ steps.getbranches.outputs.branches }}
-          push:         false
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          debug:        false
+          name: Setup
+          path: |
+            logs
 
   Check:
     needs: [Setup]
@@ -93,14 +116,13 @@ jobs:
     secrets:
       TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  Cleanup:
+  PostWorkflow:
     if: ${{ success() || failure() }}
     runs-on: ubuntu-latest
     needs: [Setup,Check]
     steps:
       - name: Check status
         env:
-          GH_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
           RESULT_UNIT:  ${{ needs.Check.result }}
           TESTS_PASSED: ${{ vars.CHERRY_PICK_CHECKS_PASSED_LABEL }}
           TESTS_FAILED: ${{ vars.CHERRY_PICK_CHECKS_FAILED_LABEL }}
@@ -122,3 +144,23 @@ jobs:
               $PR_NUMBER || :
           exit 0
 
+      - name: Create Job Summary
+        run: |
+          wget -qO asterisk-ci-actions.tar.gz \
+            https://github.com/${ACTIONS_OWNER}/${ACTIONS_REPO}/archive/refs/heads/${ACTIONS_BRANCH}.tar.gz
+          tar -xf asterisk-ci-actions.tar.gz --transform="s/^${ACTIONS_REPO}-${ACTIONS_BRANCH}/asterisk-ci-actions/g"
+
+          mkdir logs
+          ${SCRIPT_DIR}/createJobSummary.sh \
+            --repo=${REPO} \
+            --workflow-run=${WORKFLOW_RUN_ID} \
+            --tmp-dir=./run-${WORKFLOW_RUN_ID} \
+            --job-summary-output=job_summary.txt \
+            --output-dir=./logs \
+            --write-step-summary \
+            --verbose
+          if [ ! -f ./logs/job_summary.txt ] ; then
+            echo "No failures" >> ./logs/job_summary.txt
+            echo "No failures" >> "$GITHUB_STEP_SUMMARY"
+          fi
+          exit 0
diff --git a/.github/workflows/OnPRRecheck.yml b/.github/workflows/OnPRRecheck.yml
--- a/.github/workflows/OnPRRecheck.yml
+++ b/.github/workflows/OnPRRecheck.yml
@@ -1,5 +1,5 @@
 name: PRReCheck
-run-name: "PR ${{ github.event.number }} Recheck"
+run-name: "PR ${{ github.event.number }} Recheck by ${{ github.actor }}"
 on:
   pull_request_target:
     types: [ labeled ]
@@ -9,40 +9,49 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  PR_NUMBER: ${{ github.event.number }}
+  REPO:            ${{ github.repository }}
+  PR_NUMBER:       ${{ github.event.number }}
+  WORKFLOW_RUN_ID: ${{ github.run_id }}
+  SCRIPT_DIR:      ${{ github.workspace }}/asterisk-ci-actions/scripts
+  GH_TOKEN:        ${{ secrets.GITHUB_TOKEN }}
 
 jobs:
   Setup:
     if: ${{ github.event.label.name == vars.RECHECKPR_LABEL }}
     runs-on: ubuntu-latest
     outputs:
-      testsuite_test_pr:  ${{ steps.testsuitepr.outputs.testsuite_test_pr }}
+      testsuite_test_pr: ${{ steps.setup.outputs.TESTSUITE_TEST_PR }}
     steps:
-      - name: Set Label
-        id: setlabel
+      - id: setup
         env:
-          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
+          RECHECKPR_LABEL:    ${{ vars.RECHECKPR_LABEL }}
+          PR_SUBMIT_TESTS_PASSED: ${{ vars.PR_SUBMIT_TESTS_PASSED }}
+          PR_SUBMIT_TESTS_FAILED: ${{ vars.PR_SUBMIT_TESTS_FAILED }}
+          PR_SUBMIT_TESTING_IN_PROGRESS: ${{ vars.PR_SUBMIT_TESTING_IN_PROGRESS }}
+          TESTSUITE_TEST_PR_REGEX: ${{ vars.TESTSUITE_TEST_PR_REGEX }}
         run: |
-          gh pr edit --repo ${{ github.repository }} \
-            --remove-label ${{ vars.RECHECKPR_LABEL }} \
-            --remove-label ${{ vars.PR_SUBMIT_TESTS_PASSED }} \
-            --remove-label  ${{ vars.PR_SUBMIT_TESTS_FAILED }} \
-            --add-label ${{ vars.PR_SUBMIT_TESTING_IN_PROGRESS }} \
-            $PR_NUMBER || :
+          # GetScripts
+          wget -qO asterisk-ci-actions.tar.gz \
+            https://github.com/${ACTIONS_OWNER}/${ACTIONS_REPO}/archive/refs/heads/${ACTIONS_BRANCH}.tar.gz
+          tar -xf asterisk-ci-actions.tar.gz --transform="s/^${ACTIONS_REPO}-${ACTIONS_BRANCH}/asterisk-ci-actions/g"
 
-      - name: GetTestsuitePR
-        id: testsuitepr
-        uses: asterisk/asterisk-ci-actions/GetTestsuitePRFromAsteriskPR@main
-        with:
-          repo:                            ${{ github.repository }}
-          pr_number:                       ${{ github.event.number }}
-          testsuite_test_pr_regex:         ${{ vars.TESTSUITE_TEST_PR_REGEX }}
-          testsuite_test_auto_merge_regex: ${{ vars.TESTSUITE_TEST_AUTO_MERGE_REGEX }}
-          github_token:                    ${{ secrets.GITHUB_TOKEN }}
+          gh pr edit --repo ${REPO} \
+            --remove-label ${RECHECKPR_LABEL} \
+            --remove-label ${PR_SUBMIT_TESTS_PASSED} \
+            --remove-label ${PR_SUBMIT_TESTS_FAILED} \
+            --add-label ${PR_SUBMIT_TESTING_IN_PROGRESS} \
+            ${PR_NUMBER} || :
 
-  ReCheck:
-    name: ReCheck
-    needs: Setup
+          # Testsuite PR will be placed in TESTSUITE_TEST_PR in both
+          # GITHUB_ENV and GITHUB_OUTPUT by the script.
+          ${SCRIPT_DIR}/getTestsuitePRfromAsteriskPR.sh \
+            --repo=${REPO} \
+            --pr-number=${PR_NUMBER} \
+            --testsuite-pr-regex="${TESTSUITE_TEST_PR_REGEX}"
+
+  Check:
+    name: Check
+    needs: [ Setup ]
     uses: asterisk/asterisk-ci-actions/.github/workflows/AsteriskUnitGateTest.yml@main
     with:
       test_type:         prrecheck
@@ -59,15 +68,14 @@ jobs:
     secrets:
       TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  Cleanup:
+  PostWorkflow:
     if: ${{ success() || failure() }}
     runs-on: ubuntu-latest
-    needs: [Setup,ReCheck]
+    needs: [Setup,Check]
     steps:
       - name: Check status
         env:
-          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
-          RESULT_UNIT: ${{ needs.ReCheck.result }}
+          RESULT_UNIT: ${{ needs.Check.result }}
           TESTS_PASSED: ${{ vars.PR_SUBMIT_TESTS_PASSED }}
           TESTS_FAILED: ${{ vars.PR_SUBMIT_TESTS_FAILED }}
         run: |
@@ -86,4 +94,25 @@ jobs:
             --remove-label ${{ vars.PR_SUBMIT_TESTING_IN_PROGRESS }} \
             --add-label $label \
               $PR_NUMBER || :
+          exit 0
+
+      - name: Create Job Summary
+        run: |
+          wget -qO asterisk-ci-actions.tar.gz \
+            https://github.com/${ACTIONS_OWNER}/${ACTIONS_REPO}/archive/refs/heads/${ACTIONS_BRANCH}.tar.gz
+          tar -xf asterisk-ci-actions.tar.gz --transform="s/^${ACTIONS_REPO}-${ACTIONS_BRANCH}/asterisk-ci-actions/g"
+
+          mkdir logs
+          ${SCRIPT_DIR}/createJobSummary.sh \
+            --repo=${REPO} \
+            --workflow-run=${WORKFLOW_RUN_ID} \
+            --tmp-dir=./run-${WORKFLOW_RUN_ID} \
+            --job-summary-output=job_summary.txt \
+            --output-dir=./logs \
+            --write-step-summary \
+            --verbose
+          if [ ! -f ./logs/job_summary.txt ] ; then
+            echo "No failures" >> ./logs/job_summary.txt
+            echo "No failures" >> "$GITHUB_STEP_SUMMARY"
+          fi
           exit 0
diff --git a/.github/workflows/OnPRStateChanged.yml b/.github/workflows/OnPRStateChanged.yml
--- a/.github/workflows/OnPRStateChanged.yml
+++ b/.github/workflows/OnPRStateChanged.yml
@@ -23,6 +23,13 @@ concurrency:
   group: check-${{ github.event.number }}
   cancel-in-progress: true
 
+env:
+  REPO:      ${{ github.repository }}
+  PR_NUMBER: ${{ github.event.number }}
+  WORKFLOW_RUN_ID:   ${{ github.run_id }}
+  SCRIPT_DIR:        ${{ github.workspace }}/asterisk-ci-actions/scripts
+  GH_TOKEN:          ${{ secrets.TOKEN }}
+
 jobs:
 #
 # Pull requests created from forked respositories don't have access
@@ -33,37 +40,31 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       vars:  ${{ steps.setvars.outputs.control_data }}
-      testsuite_test_pr:  ${{ steps.testsuitepr.outputs.testsuite_test_pr }}
+      testsuite_test_pr:  ${{ steps.setup.outputs.testsuite_test_pr }}
     steps:
       - id: setvars
         uses: asterisk/asterisk-ci-actions/GetRepoControlData@main
         with:
           repo: ${{ github.event.repository.name }}
 
-      - id: wait
+      - id: setup
         env:
           PR_STATE_CHANGE_DELAY_SEC: ${{ fromJSON(steps.setvars.outputs.control_data).PR_STATE_CHANGE_DELAY_SEC || 120 }}
+          TESTSUITE_TEST_PR_REGEX: ${{ fromJSON(steps.setvars.outputs.control_data).TESTSUITE_TEST_PR_REGEX }}
         run: |
           echo "Waiting for ${PR_STATE_CHANGE_DELAY_SEC} seconds to give user a chance to add PR comments"
           sleep ${PR_STATE_CHANGE_DELAY_SEC}
-          exit 0
 
-      - name: GetTestsuitePR
-        id: testsuitepr
-        uses: asterisk/asterisk-ci-actions/GetTestsuitePRFromAsteriskPR@main
-        with:
-          repo:                            ${{ github.repository }}
-          pr_number:                       ${{ github.event.number }}
-          testsuite_test_pr_regex:         ${{ fromJSON(steps.setvars.outputs.control_data).TESTSUITE_TEST_PR_REGEX }}
-          testsuite_test_auto_merge_regex: ${{ fromJSON(steps.setvars.outputs.control_data).TESTSUITE_TEST_AUTO_MERGE_REGEX }}
-          github_token:                    ${{ secrets.GITHUB_TOKEN }}
+          wget -qO asterisk-ci-actions.tar.gz \
+            https://github.com/${ACTIONS_OWNER}/${ACTIONS_REPO}/archive/refs/heads/${ACTIONS_BRANCH}.tar.gz
+          tar -xf asterisk-ci-actions.tar.gz --transform="s/^${ACTIONS_REPO}-${ACTIONS_BRANCH}/asterisk-ci-actions/g"
 
-      - name: DumpEnvironment
-        if: ${{ fromJSON(steps.setvars.outputs.control_data).RUN_DUMP_ENV }}
-        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main
-        with:
-          action-vars: ${{ toJSON(steps.setvars.outputs) }}
-          action-inputs: ${{ toJSON(steps.testsuitepr.outputs) }}
+          # Testsuite PR will be placed in TESTSUITE_TEST_PR in both
+          # GITHUB_ENV and GITHUB_OUTPUT by the script.
+          ${SCRIPT_DIR}/getTestsuitePRfromAsteriskPR.sh \
+            --repo=${REPO} \
+            --pr-number=${PR_NUMBER} \
+            --testsuite-pr-regex="${TESTSUITE_TEST_PR_REGEX}"
 
   Check:
     name: Check
@@ -82,4 +83,30 @@ jobs:
       gatetest_commands: ${{ fromJSON(needs.Setup.outputs.vars).GATETEST_COMMANDS }}
     secrets:
       TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  PostWorkflow:
+    if: ${{ success() || failure() }}
+    runs-on: ubuntu-latest
+    needs: [Setup,Check]
+    steps:
+      - name: Create Job Summary
+        run: |
+          wget -qO asterisk-ci-actions.tar.gz \
+            https://github.com/${ACTIONS_OWNER}/${ACTIONS_REPO}/archive/refs/heads/${ACTIONS_BRANCH}.tar.gz
+          tar -xf asterisk-ci-actions.tar.gz --transform="s/^${ACTIONS_REPO}-${ACTIONS_BRANCH}/asterisk-ci-actions/g"
+
+          mkdir logs
+          ${SCRIPT_DIR}/createJobSummary.sh \
+            --repo=${REPO} \
+            --workflow-run=${WORKFLOW_RUN_ID} \
+            --tmp-dir=./run-${WORKFLOW_RUN_ID} \
+            --job-summary-output=job_summary.txt \
+            --output-dir=./logs \
+            --write-step-summary \
+            --verbose
+          if [ ! -f ./logs/job_summary.txt ] ; then
+            echo "No failures" >> ./logs/job_summary.txt
+            echo "No failures" >> "$GITHUB_STEP_SUMMARY"
+          fi
+          exit 0
 
