Workflow renames

diff --git a/.github/workflows/PRPostCheckActions.yml b/.github/workflows/PRPostCheckActions.yml
--- a/.github/workflows/PRPostCheckActions.yml
+++ b/.github/workflows/PRPostCheckActions.yml
@@ -1,8 +1,8 @@
-name: PRSubmitActions
-run-name: "PRSubmitActions: Test ${{github.event.action}}"
+name: PRPostCheckActions
+run-name: "PRPostCheckActions ${{github.event.workflow.name}} ${{github.event.action}}"
 on:
   workflow_run:
-    workflows: [PRSubmitTests]
+    workflows: [PRStateChanged,PRRecheck]
     types:
       - requested
       - completed
@@ -12,26 +12,31 @@ env:
   REPO:       ${{ github.repository }}
 
 jobs:
-  PRSubmitActions:
+  PRPostCheckActions:
     runs-on: ubuntu-latest
+    outputs:
+      PR_NUMBER:     ${{ steps.getpr.outputs.PR_NUMBER }}
     steps:
+      - name: DumpEnvironment
+        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main
+
       - name: Get PR Number
         id: getpr
-        uses: actions/github-script@v7
-        with:
-          retries: 5
-          script: |
-            let search = `repo:${context.repo.owner}/${context.repo.repo} ${context.payload.workflow_run.head_sha}`; 
-            let prs = await github.rest.search.issuesAndPullRequests({
-                 q: search,
-              });
-            if (prs.data.total_count == 0) {
-              core.setFailed(`Unable to get PR for ${context.payload.workflow_run.head_sha}`);
-              return;
-            }
-            let pr_number = prs.data.items[0].number;
-            core.setOutput('pr_number', pr_number);
-            return;
+        env:
+          GH_TOKEN: ${{ github.token }}
+          SHA: ${{github.event.workflow_run.head_sha}}
+        run: |
+          PR_NUMBER=$(gh -R $REPO search prs $SHA --json number --jq '.[].number')
+          if [ -z "$PR_NUMBER" ] ; then
+            echo "::error::Unable to find PR number"
+            exit 1
+          fi
+          if [[ "$PR_NUMBER" =~ ^[0-9]+$ ]] ; then
+            echo "PR_NUMBER=${PR_NUMBER}" >>${GITHUB_OUTPUT}
+            exit 0
+          fi
+          echo "::error::PR number '$PR_NUMBER' not valid"
+          exit 1
 
       - name: Set Label
         id: setlabel
@@ -115,35 +120,35 @@ jobs:
             })
             return;
 
-      - name: Add reviewers
-        if: github.event.action == 'completed'
-        uses: actions/github-script@v7
-        env:
-          PR_NUMBER: ${{steps.getpr.outputs.PR_NUMBER}}
-          REVIEWERS: ${{vars.PR_REVIEWERS}}
-        with:
-          retries: 5
-          github-token: ${{ secrets.ASTERISKTEAM_PAT }}
-          script: |
-            let rs = JSON.parse(process.env.REVIEWERS.length ? process.env.REVIEWERS : '[]');
-            let users = [];
-            let teams = [];
-            for (const r of rs) {
-              if (r.indexOf("/") > 0) {
-                teams.push(r.split('/')[1]);
-              } else {
-                users.push(r);
-              }
-            }
-            if (teams.length > 0 || users.length > 0) {
-              core.info(`Adding user reviewers ${users}`);
-              core.info(`Adding team reviewers ${teams}`);
-              await github.rest.pulls.requestReviewers({
-                pull_number: process.env.PR_NUMBER,
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                reviewers: users,
-                team_reviewers: teams
-              });
-            }
-            return;
+#      - name: Add reviewers
+#        if: github.event.action == 'completed'
+#        uses: actions/github-script@v7
+#        env:
+#          PR_NUMBER: ${{steps.getpr.outputs.PR_NUMBER}}
+#          REVIEWERS: ${{vars.PR_REVIEWERS}}
+#        with:
+#          retries: 5
+#          github-token: ${{ secrets.ASTERISKTEAM_PAT }}
+#          script: |
+#            let rs = JSON.parse(process.env.REVIEWERS.length ? process.env.REVIEWERS : '[]');
+#            let users = [];
+#            let teams = [];
+#            for (const r of rs) {
+#              if (r.indexOf("/") > 0) {
+#                teams.push(r.split('/')[1]);
+#              } else {
+#                users.push(r);
+#              }
+#            }
+#            if (teams.length > 0 || users.length > 0) {
+#              core.info(`Adding user reviewers ${users}`);
+#              core.info(`Adding team reviewers ${teams}`);
+#              await github.rest.pulls.requestReviewers({
+#                pull_number: process.env.PR_NUMBER,
+#                owner: context.repo.owner,
+#                repo: context.repo.repo,
+#                reviewers: users,
+#                team_reviewers: teams
+#              });
+#            }
+#            return;
