Add OnPRLabeled.yml

diff --git a/.github/workflows/PRSubmitTests.yml b/.github/workflows/PRSubmitTests.yml
--- a/.github/workflows/PRSubmitTests.yml
+++ b/.github/workflows/PRSubmitTests.yml
@@ -38,6 +38,20 @@ jobs:
   PRSUnitTests:
     needs: PRSGetControlData
     runs-on: ubuntu-latest
+    services:
+      # Label used to access the service container
+      postgres-asterisk:
+        # Docker Hub image
+        image: postgres
+        # Provide the password for postgres
+        env:
+          POSTGRES_PASSWORD: postgres
+        # Set health checks to wait until postgres has started
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
     env:
       UNITTEST_COMMAND: ${{ fromJSON(needs.PRSGetControlData.outputs.control_data).UNITTEST_COMMAND }}
     steps:
@@ -49,66 +63,66 @@ jobs:
           base_branch:       ${{env.BRANCH}}
           unittest_command:  ${{env.UNITTEST_COMMAND}}
 
-  PRSGateTestMatrix:
-    runs-on: ubuntu-latest
-    needs: PRSGetControlData
-    continue-on-error: false
-    strategy:
-      fail-fast: false
-      matrix:
-        group: ${{ fromJSON(fromJSON(needs.PRSGetControlData.outputs.control_data).GATETEST_LIST) }}
-    env:
-      TESTSUITE_REPO:    "${{ fromJSON(needs.PRSGetControlData.outputs.control_data).TESTSUITE_REPO }}"
-      GATETEST_COMMANDS: "${{ fromJSON(needs.PRSGetControlData.outputs.control_data).GATETEST_COMMANDS }}"
-      GATETEST_COMMAND: "${{ toJSON(fromJSON(fromJSON(needs.PRSGetControlData.outputs.control_data).GATETEST_COMMANDS)[matrix.group]) }}"
-    steps:
-      - id: runtest
-        name: Run Gate Tests for ${{ matrix.group }}
-        uses: asterisk/asterisk-ci-actions/AsteriskGateComposite@main
-        with:
-          test_type:         Gate
-          asterisk_repo:     ${{env.ASTERISK_REPO}}
-          pr_number:         ${{env.PR_NUMBER}}
-          base_branch:       ${{env.BRANCH}}
-          testsuite_repo:    ${{env.TESTSUITE_REPO}}
-          gatetest_group:    ${{matrix.group}}
-          gatetest_command:  ${{env.GATETEST_COMMAND}}
-
-  PRSTestResults:
-    if: always()
-    runs-on: ubuntu-latest
-    needs: [PRSUnitTests,PRSGateTestMatrix]
-    steps:
-      - name: Check test matrix status
-        env:
-          RESULT_UNIT: ${{ needs.PRSUnitTests.result }}
-          RESULT_GATE: ${{ needs.PRSGateTestMatrix.result }}
-        run: |
-          declare -i rc=0
-          echo "all results: ${{ toJSON(needs.*.result) }}"
-          case $RESULT_UNIT in
-            success)
-              echo "::notice::Unit tests passed"
-              ;;
-            skipped)
-              echo "::error::Unit tests were skipped because of an earlier failure"
-              rc+=1
-              ;;
-            *)
-              echo "::error::One or more unit tests failed ($RESULT_UNIT)"
-              rc+=1
-          esac
-          case $RESULT_GATE in
-            success)
-              echo "::notice::Gate tests passed"
-              ;;
-            skipped)
-              echo "::error::Gate tests were skipped because of an earlier failure"
-              rc+=1
-              ;;
-            *)
-              echo "::error::One or more gate tests failed ($RESULT_GATE)"
-              rc+=1
-          esac
-          echo "::notice::Final result code: $rc"
-          exit $rc
+#  PRSGateTestMatrix:
+#    runs-on: ubuntu-latest
+#    needs: PRSGetControlData
+#    continue-on-error: false
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        group: ${{ fromJSON(fromJSON(needs.PRSGetControlData.outputs.control_data).GATETEST_LIST) }}
+#    env:
+#      TESTSUITE_REPO:    "${{ fromJSON(needs.PRSGetControlData.outputs.control_data).TESTSUITE_REPO }}"
+#      GATETEST_COMMANDS: "${{ fromJSON(needs.PRSGetControlData.outputs.control_data).GATETEST_COMMANDS }}"
+#      GATETEST_COMMAND: "${{ toJSON(fromJSON(fromJSON(needs.PRSGetControlData.outputs.control_data).GATETEST_COMMANDS)[matrix.group]) }}"
+#    steps:
+#      - id: runtest
+#        name: Run Gate Tests for ${{ matrix.group }}
+#        uses: asterisk/asterisk-ci-actions/AsteriskGateComposite@main
+#        with:
+#          test_type:         Gate
+#          asterisk_repo:     ${{env.ASTERISK_REPO}}
+#          pr_number:         ${{env.PR_NUMBER}}
+#          base_branch:       ${{env.BRANCH}}
+#          testsuite_repo:    ${{env.TESTSUITE_REPO}}
+#          gatetest_group:    ${{matrix.group}}
+#          gatetest_command:  ${{env.GATETEST_COMMAND}}
+#
+#  PRSTestResults:
+#    if: always()
+#    runs-on: ubuntu-latest
+#    needs: [PRSUnitTests,PRSGateTestMatrix]
+#    steps:
+#      - name: Check test matrix status
+#        env:
+#          RESULT_UNIT: ${{ needs.PRSUnitTests.result }}
+#          RESULT_GATE: ${{ needs.PRSGateTestMatrix.result }}
+#        run: |
+#          declare -i rc=0
+#          echo "all results: ${{ toJSON(needs.*.result) }}"
+#          case $RESULT_UNIT in
+#            success)
+#              echo "::notice::Unit tests passed"
+#              ;;
+#            skipped)
+#              echo "::error::Unit tests were skipped because of an earlier failure"
+#              rc+=1
+#              ;;
+#            *)
+#              echo "::error::One or more unit tests failed ($RESULT_UNIT)"
+#              rc+=1
+#          esac
+#          case $RESULT_GATE in
+#            success)
+#              echo "::notice::Gate tests passed"
+#              ;;
+#            skipped)
+#              echo "::error::Gate tests were skipped because of an earlier failure"
+#              rc+=1
+#              ;;
+#            *)
+#              echo "::error::One or more gate tests failed ($RESULT_GATE)"
+#              rc+=1
+#          esac
+#          echo "::notice::Final result code: $rc"
+#          exit $rc
