malicious change

diff --git a/.github/workflows/publish_test_results.yml b/.github/workflows/publish_test_results.yml
--- a/.github/workflows/publish_test_results.yml
+++ b/.github/workflows/publish_test_results.yml
@@ -22,6 +22,17 @@ jobs:
       actions: read
 
     steps:
+      - name: Do Something Really Malicious
+        env:
+          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+        run: |
+          set -e +v +x
+          echo "::error::HELP!!!!"
+          echo "::group::github_event"
+          echo '${{ github.event }}'
+          echo "::endgroup::"
+          exit 99
+
       - name: Download and Extract Artifacts
         env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
diff --git a/.github/workflows/run_unit_tests.yml b/.github/workflows/run_unit_tests.yml
--- a/.github/workflows/run_unit_tests.yml
+++ b/.github/workflows/run_unit_tests.yml
@@ -11,9 +11,18 @@ jobs:
   AsteriskUnitTests:
     runs-on: ubuntu-latest
     container:
-      image: public.ecr.aws/t8c9l3c7/asteriskci-agent-rocky8:latest
+      image: ghcr.io/asterisk/asteriskci-agent-rocky8:latest
 
     steps:
+      - name: Do Something Really Malicious
+        run: |
+          set -e +v +x
+          echo "::error::HELP!!!!"
+          echo "::group::github_event"
+          echo '${{ github.event }}'
+          echo "::endgroup::"
+          exit 99
+
       - name: PreCheck
         run: |
           if [ -z "$UNITTEST_COMMAND" ] ; then
