Update pro

diff --git a/.github/workflows/pull_request_opened.yml b/.github/workflows/pull_request_opened.yml
--- a/.github/workflows/pull_request_opened.yml
+++ b/.github/workflows/pull_request_opened.yml
@@ -1,4 +1,4 @@
-name: Asterisk Unit Tests
+name: Pull Request Opened
 run-name: ${{ github.actor }} has submitted a pull request
 on:
   pull_request:
@@ -6,15 +6,60 @@ on:
   
 
 jobs:
-  CheckForIssue:
+  SimpleChecks:
     runs-on: ubuntu-latest
+#    container:
+#      image: public.ecr.aws/t8c9l3c7/asteriskci-agent-rocky8:latest
     steps:
-      - name:
+      - name: Install needed progs
         run: |
-          echo "::group::github_trigger_event"
-          echo '${{ toJSON(github.event) }}' > asterisk/event.json
-          echo "::endgroup::"
-          echo "::group::env"
-          echo '${{ toJSON(env) }}' > asterisk/env.json
-          echo "::endgroup::"
+          sudo apt-get install jq -y
 
+      - name: Check for labels
+        run: |
+          LABELS=$( echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | jq -r '.[]')
+          echo "LABELS: $LABELS"
+          has_type=0
+          has_cherry=0
+          rc=0
+          for l in $LABELS ; do
+            [[ $l =~ (bug|enhancement|documentation) ]] && has_type+=1
+            [[ $l =~ (cherry-pick-.*) ]] && has_cherry+=1
+          done
+          if [ $has_type -eq 0 ] ; then
+            rc=1
+            echo "::error::The PR needs a label that's one of bug, enhancement, or documentation"
+          fi
+          if [ $has_type -gt 1 ] ; then
+            rc=1
+            echo "::error::The PR can only have one of bug, enhancement, or documentation labels"
+          fi
+          if [ $has_cherry -eq 0 ] ; then
+            rc=1
+            echo "::error::The PR needs at least one cherry-pick-* label"
+          fi
+          if [ $rc -eq 0 ] ; then
+            echo "::notice::The PR has good labels"
+          fi
+          exit $rc
+
+      - name: Check for issue
+        env:
+          BODY: ${{ toJSON(github.event.pull_request.body) }}
+        run: |
+          echo "BODY: $BODY"
+          msg=$(echo "$BODY" | sed -n -r -e "s/(Closes|Resolves):\s+#([0-9]+)/::notice::The PR \1 issue \2/gp")
+          if [ -n "$msg" ] ; then
+            echo "$msg"
+            has_issue=1
+            rc=0
+          else
+          	echo "::error::The PR does not have an issue associated with it"
+            has_issue=0
+            rc=1
+          fi
+          exit $rc
+
+  UnitTests:
+    needs: SimpleChecks
+    uses: ./.github/workflows/run_unit_tests.yml
